# Generated by Django 3.0.6 on 2020-05-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('clientes', '0004_auto_20200527_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEncomenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Estado de Encomenda',
                'verbose_name_plural': 'Estados de Encomendas',
            },
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('valor', models.FloatField(verbose_name='Valor (em Euros)')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente',
                                              verbose_name='Cliente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to='encomendas.EstadoEncomenda', verbose_name='Estado')),
                ('metodo_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                       to='clientes.MetodoPagamento',
                                                       verbose_name='Método de Pagamento')),
            ],
            options={
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
            },
        ),
    ]
