# Generated by Django 3.0.6 on 2020-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='observacoes',
            field=models.TextField(default='', verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomenda',
            name='portes',
            field=models.BooleanField(default=False, verbose_name='Portes?'),
            preserve_default=False,
        ),
    ]
