# Generated by Django 3.0.6 on 2020-05-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
                'verbose_name_plural': 'Métodos de Pagamento',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='MotivoChamadaTelefonica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Motivo de Chamada Telefónica',
                'verbose_name_plural': 'Motivos de Chamadas Telefónicas',
                'ordering': ['-descricao'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('telefone', models.CharField(max_length=13, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cartao_cidadao', models.CharField(blank=True, max_length=15, verbose_name='Cartão de Cidadão')),
                ('morada', models.CharField(max_length=200, verbose_name='Morada (Rua, Avenida, ...)')),
                ('codigo_postal', models.CharField(max_length=8, verbose_name='Código-Postal')),
                ('localidade', models.CharField(max_length=50, verbose_name='Localidade')),
                ('pais', models.CharField(max_length=25, verbose_name='País')),
                ('perfil_facebook', models.CharField(blank=True, max_length=100, verbose_name='Perfil no Facebook')),
                ('registado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('metodo_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                       to='clientes.MetodoPagamento',
                                                       verbose_name='Método de Pagamento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-registado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChamadaTelefonica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente',
                                              verbose_name='Cliente')),
                ('motivo',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.MotivoChamadaTelefonica',
                                   verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Chamada Telefónica',
                'verbose_name_plural': 'Chamadas Telefónicas',
                'ordering': ['-data'],
            },
        ),
    ]
