# Generated by Django 3.0.6 on 2020-05-27 18:06

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('clientes', '0002_auto_20200527_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
