# Generated by Django 3.0.6 on 2020-05-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clientes', '0003_auto_20200527_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadatelefonica',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='chamadatelefonica',
            name='hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
    ]
